import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "BS Friend",
  description: "Generated by adAstraPaul",
};

export const wallauUnzialBold = localFont({
  src: '../public/WallauUnzialBold.ttf',
})

export const lucidaBlackletterRegular = localFont({
  src: '../public/Lucida-Blackletter-Regular.woff',
})

export const cormorantGaramondRegular = localFont({
  src: '../public/CormorantGaramond-Regular.ttf',
})

export const playfairDisplay = localFont({
  src: '../public/PlayfairDisplay-VariableFont.ttf',
})

export const cinzel = localFont({
  src: '../public/Cinzel-VariableFont.ttf',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        {children}
      </body>
    </html>
  );
}
